using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ThumbsApi.Models
{
    /// <summary>
    /// ThumbBase
    /// </summary>
    public class ThumbBase
    {
        /// <summary>
        /// Id generated by database
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; protected set; }

        /// <summary>
        /// Pid of staff who submitted thumb
        /// </summary>
        [MinLength(7)]
        [MaxLength(7)]
        public string Pid { get; internal set; }

        /// <summary>
        /// Date thumb was submitted
        /// </summary>
        [Required]
        public DateTime Date { get; protected set; } = DateTime.Now;

        /// <summary>
        /// The thumb rating (up = true, down = false)
        /// </summary>
        [Required]
        public bool Rating { get; set; }

        /// <summary>
        /// The product thumbed
        /// </summary>
        [Required]
        [MaxLength(100)]
        public string Product { get; set; }

        /// <summary>
        /// The group the product is from
        /// </summary>
        [Required]
        [MaxLength(100)]
        public string Group { get; set; }


        /// <summary>
        /// The endpoint of the thumb
        /// </summary>
        [Required]
        [MaxLength(255)]
        public string EndPoint { get; set; } 
    }
}
