// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThumbsApi.Contexts;

namespace ThumbsApi.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20181205180440_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ThumbsApi.Models.Deletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .IsFixedLength(true)
                        .HasMaxLength(7)
                        .IsUnicode(false);

                    b.Property<DateTime>("DeletedTime");

                    b.Property<string>("EndPoint")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Pid")
                        .IsFixedLength(true)
                        .HasMaxLength(7)
                        .IsUnicode(false);

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("Rating");

                    b.HasKey("Id");

                    b.ToTable("Deletions");
                });

            modelBuilder.Entity("ThumbsApi.Models.Thumb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("EndPoint")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Pid")
                        .IsFixedLength(true)
                        .HasMaxLength(7)
                        .IsUnicode(false);

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("Rating");

                    b.HasKey("Id");

                    b.ToTable("Thumbs");
                });
#pragma warning restore 612, 618
        }
    }
}
