// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThumbsApi.Contexts;

namespace ThumbsApi.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20181127113118_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ThumbsApi.Models.Thumb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("EndPoint");

                    b.Property<string>("Group")
                        .HasMaxLength(255);

                    b.Property<string>("Pid")
                        .HasMaxLength(7);

                    b.Property<string>("Product");

                    b.Property<bool>("Rating");

                    b.HasKey("Id");

                    b.ToTable("Thumbs");
                });
#pragma warning restore 612, 618
        }
    }
}
